// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwicxpFqQC2ZPEsZg7zl7hPWQA87MEPg',
    appId: '1:710933644346:web:01f709d4cf47e7f2d12103',
    messagingSenderId: '710933644346',
    projectId: 'tasmeea-497bf',
    authDomain: 'tasmeea-497bf.firebaseapp.com',
    storageBucket: 'tasmeea-497bf.firebasestorage.app',
    measurementId: 'G-P8DRKBJFMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnfGLTbjOubTv2SYM4CQvWS9KPHIgPQo',
    appId: '1:710933644346:android:8e46aa31c3a9ae3ed12103',
    messagingSenderId: '710933644346',
    projectId: 'tasmeea-497bf',
    storageBucket: 'tasmeea-497bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDade8e4t2HU8pTLhYs0crhp_uJZd3-rEY',
    appId: '1:710933644346:ios:83222f3ef73d3c74d12103',
    messagingSenderId: '710933644346',
    projectId: 'tasmeea-497bf',
    storageBucket: 'tasmeea-497bf.firebasestorage.app',
    iosBundleId: 'com.qurantasmee3.quranTasmee3',
  );
}
