"""Extract CMVN stats from streaming_global_cmvn.npz → print Dart constants.

Usage:
    pip install numpy
    python tools/asr/export_cmvn.py \
        --npz assets/models/streaming/streaming_global_cmvn.npz

Copy the printed Dart code into lib/app/data/cmvn_data.dart.

Expected keys in the npz: 'tlog_mean' and 'tlog_std' (shape [80]).
If the file uses different key names they are printed so you can identify them.
"""

import argparse
import sys

try:
    import numpy as np
except ImportError:
    sys.exit("numpy not installed.  Run: pip install numpy")


def _dart_list(arr, name):
    vals = ", ".join(f"{v:.8f}" for v in arr)
    return f"const List<double> {name} = [{vals}];"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npz", default="assets/models/streaming/streaming_global_cmvn.npz")
    args = ap.parse_args()

    data = np.load(args.npz)
    print("Keys in npz:", list(data.keys()))

    # Try common key names used by NeMo exports.
    mean_key = next((k for k in data if "mean" in k.lower()), None)
    std_key  = next((k for k in data if "std"  in k.lower() or "var" in k.lower()), None)

    if mean_key is None or std_key is None:
        print("Could not detect mean/std keys. Available keys:", list(data.keys()))
        for k in data:
            print(f"  {k}: shape={data[k].shape} dtype={data[k].dtype}")
        sys.exit(1)

    mean = data[mean_key].flatten().astype(float)
    std  = data[std_key ].flatten().astype(float)

    # If std key actually contains variance, convert.
    if "var" in std_key.lower() and "std" not in std_key.lower():
        std = np.sqrt(std + 1e-8)
        print(f"Note: '{std_key}' interpreted as variance → converted to std.")

    print(f"\nmean key: '{mean_key}' shape={mean.shape}")
    print(f"std  key: '{std_key}'  shape={std.shape}")

    if len(mean) != 80 or len(std) != 80:
        print(f"WARNING: expected 80-dim features, got mean={len(mean)} std={len(std)}")

    print("\n--- Copy this into lib/app/data/cmvn_data.dart ---\n")
    print("// Auto-generated by tools/asr/export_cmvn.py — do not edit manually.")
    print("// Source: streaming_global_cmvn.npz")
    print("")
    print(_dart_list(mean, "cmvnMean"))
    print("")
    print(_dart_list(std,  "cmvnStd"))
    print("\n--- end ---")


if __name__ == "__main__":
    main()
